### PR TITLE
Update bug_report.yml

### PR DESCRIPTION
**Pull request by lipmaneth**
## Description

_Concise description of proposed changes_

## Additional Information

- [x] I read the [contributing docs](https://github.com/GuardianUI/guardianui/blob/main/CONTRIBUTING.md) (if this is your first contribution)

### CODE REVIEW

**Comment by lipmaneth** [comment]
@0xLienid I've made changes to the bug report template. Take a look and let's see if we can close this topic.

**Comment by lipmaneth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xLienid** [comment]
this looks good to me

**Review by 0xLienid — APPROVED** [review]

**Comment by 0xLienid** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lipmaneth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xLienid** [comment]
recheck

**Comment by lipmaneth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by lipmaneth** [comment]
recheck

**Pull request merged**
