### PR TITLE
README adjustments

### PR DESCRIPTION
**Pull request by 0xLienid**
## Description

README adjustments

## Additional Information

- [X] I read the [contributing docs](https://github.com/GuardianUI/guardianui/blob/main/CONTRIBUTING.md) (if this is your first contribution)

### CODE REVIEW

**Review by lipmaneth — COMMENTED** [review]
@0xLienid see a cpl questions/suggestions.

**Comment by 0xLienid** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by 0xLienid** [comment]
recheck

**Comment by lipmaneth** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by lipmaneth — APPROVED** [review]
looks good!

**Pull request merged**
